version: '3'

services:
  bundle_app:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    container_name: bundle_app_dev
    environment:
      NEXT_CONFIG_PATH: server/config/next.config.js
    volumes:
      - ./:/app
      - /app/node_modules
