version: '3'

services:
  bundle_app:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    container_name: bundle_app
    restart: unless-stopped
    env_file: ./.env
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - ${PORT}:${PORT}
    expose:
      - ${PORT}
    networks:
      - bundle_net

networks:
  bundle_net:
    driver: bridge
