version: '3'

services:
  bundle_app:
    build:
      context: ./
    container_name: bundle_app
    restart: unless-stopped
    env_file: ./.env
    environment:
      NEXT_CONFIG_PATH: dist/server/config/next.config.js
    ports:
      - ${PORT}:${PORT}
